### PR TITLE
Add score feedback

### PR DESCRIPTION
**Pull request by alexandrascript**
Another set of details from the [support site](https://support.perspectiveapi.com/s/article/score-feedback) which belong in these docs.

### CODE REVIEW

**Comment by alexandrascript** [comment]
This should not be merged until https://github.com/conversationai/perspectiveapi/pull/75 is.

**Comment by oliviaredfield** [comment]
We do have a feedback section in the methods section of the  api_reference doc, but it doesn't include info about the form option. https://github.com/conversationai/perspectiveapi/blob/master/api_reference.md#sending-feedback-suggestcommentscore

Should we just update there for now, but consider breaking out these sections in a future iteration?

**Comment by alexandrascript** [comment]
@oliviaredfield the reference serves two purposes -- in the API doc, it's to explain how that feature works in development. For this document, it's adding on relevant content to a page that already exists, explaining normalization. This is more conceptual rather than actionable, though the ability to process action is present.

I think it should be in both places, but if you firmly disagree, I will remove it from here outside of a mention of existence.

**Comment by oliviaredfield** [comment]
SGTM to have it in both places!

**Pull request merged**
